---
# Check if Burp Suite Pro is already installed
- name: Check if Burp Suite Pro is already installed
  ansible.builtin.stat:
    path: "{{ install_directory }}"
  register: burp_suite_directory

- name: Install Burp Suite Pro
  block:
    - name: Grab Burp Suite Pro installer and license from S3
      ansible.builtin.aws_s3:
        bucket: "{{ third_party_bucket_name }}"
        object: "{{ item }}"
        dest: /tmp/{{ item }}
        mode: get
      become: no
      delegate_to: localhost
      loop:
        - "{{ installer_object_name }}"
        - "{{ license_object_name }}"

    - name: Copy the Burp Suite Pro installer
      ansible.builtin.copy:
        dest: /tmp/{{ installer_object_name }}
        mode: 0700
        src: /tmp/{{ installer_object_name }}

    - name: Install Burp Suite Pro installation prerequisites
      ansible.builtin.package:
        name: "{{ installation_prerequisites }}"

    - name: Install Burp Suite Pro
      ansible.builtin.expect:
        command: /tmp/{{ installer_object_name }}
        creates: "{{ install_directory }}"
        responses:
          # $ sudo ./burpsuite_pro_linux_v2020_11.sh
          # Unpacking JRE ...
          # Starting Installer ...
          # This will install Burp Suite Professional on your computer.
          # OK [o, Enter], Cancel [c]
          #
          # Click Next to continue, or Cancel to exit Setup.
          # Select the folder where you would like Burp Suite Professional to be
          # installed, then click Next.
          # Where should Burp Suite Professional be installed?
          # [/usr/local/BurpSuitePro]
          #
          # Create symlinks?
          # Yes [y, Enter], No [n]
          #
          # Select the folder where you would like Burp Suite Professional to create symlinks, then click Next.
          # [/usr/local/bin]
          #
          # Extracting files ...
          # Setup has finished installing Burp Suite Professional on your computer.
          # Finishing installation ...
          "This will install Burp Suite Professional on your computer\\.": o
          "Where should Burp Suite Professional be installed\\?": "{{ install_directory }}"
          "Create symlinks\\?": "y"
          "Select the folder where you would like Burp Suite Professional to create symlinks, then click Next": "{{ symlinks_directory }}"
        timeout: 300

    # We can't use the ansible.builtin.expect module here because the
    # licensing process outputs the entire license text, which
    # overflows the default input buffer size of 2000 bytes.  Hence we
    # need to increase the input buffer size for expect, and this
    # cannot be done via the ansible.builtin.expect module.
    - name: License Burp Suite Pro
      ansible.builtin.shell: |
        # $ ./jre/bin/java -Djava.awt.headless=true -jar ./burpsuite_pro.jar
        # Burp Suite Professional Terms & Conditions of Supply
        #
        # <snip>
        # License text
        # </snip>
        # Do you accept the license agreement? (y/n)
        # y
        # This version of Burp requires a license key. To continue, please paste your license key below.
        # <license key>
        # Burp will now attempt to contact the license server and activate your license. This will require Internet access.
        # NOTE: license activations are monitored. If you perform too many activations, further activations for this license may be prevented.
        # Enter preferred activation method (o=online activation; m=manual activation; r=re-enter license key)
        # o
        # Your license is successfully installed and activated.

        # Increase the input buffer size from 2000 to 10000 bytes
        match-max 10000
        spawn ./jre/bin/java -Djava.awt.headless=true -jar ./burpsuite_pro.jar

        expect "Do you accept the license agreement\\?"
        send "y\n"

        expect "To continue, please paste your license key below\\."
        send "{{ lookup('file', '/tmp/' + license_object_name) }}"

        expect "Enter preferred activation method"
        send "o\n"
      args:
        chdir: "{{ install_directory }}"
        executable: /usr/bin/expect
      become_user: "{{ item }}"
      loop: "{{ users }}"

    - name: Delete local copies of Burp Suite Pro installer and license file
      ansible.builtin.file:
        path: /tmp/{{ item }}
        state: absent
      become: no
      delegate_to: localhost
      loop:
        - "{{ installer_object_name }}"
        - "{{ license_object_name }}"

    # The licensing process appears to delete the license file for you
    - name: Delete remote copy of Burp Suite Pro installer
      ansible.builtin.file:
        path: /tmp/{{ installer_object_name }}
        state: absent

  when: not burp_suite_directory.stat.exists
