---
# The name of the AWS S3 bucket where third-party software is located
burp_suite_pro_third_party_bucket_name: cisa-cool-third-party-production

# The name of the S3 object corresponding to the Burp Suite Pro Linux
# installer
burp_suite_pro_installer_object_name: burpsuite_pro_linux.sh

# Prerequisites needed to install Burp Suite Pro
burp_suite_pro_installation_prerequisites:
  # The installer application requires this
  - libfreetype6
  # This is required for the ansible.builtin.expect module
  - python3-pexpect

# The directory where Burp Suite Pro should be installed
burp_suite_pro_install_directory: /usr/local/BurpSuitePro

# The directory where symlinks to the Burp Suite Pro executables
# should be created
burp_suite_pro_symlinks_directory: /usr/local/bin
