---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-burp-suite-pro
      ansible.builtin.include_role:
        name: ansible-role-burp-suite-pro
      vars:
        burp_suite_pro_third_party_bucket_name: "{{ lookup('env', 'THIRD_PARTY_BUCKET') }}"
